# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /bbs

spring:
  # 运行环境配置
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${faramita.datasource.url}
    username: ${faramita.datasource.username}
    password: ${faramita.datasource.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

# MyBatis-Plus配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: online.faramita.bbs.entity
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名

# jwt配置
jwt: 
  secret: ${faramita.jwt.secret}
  expire: ${faramita.jwt.expire}
  header: ${faramita.jwt.header}

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  default-count: true
  support-methods-arguments: true

# Swagger3配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # 设置Swagger UI的访问路径
    disable-swagger-default-url: true 
    display-request-duration: true  # 显示请求持续时间
  packages-to-scan: online.faramita.bbs.controller  # 指定要扫描的包

faramita:
  # 文件存储位置
  file:
    avatar:
      root-path: ${faramita.file.avatar.root-path}
      max-size: ${faramita.file.avatar.max-size}
      expire: ${faramita.file.avatar.expire}
    image:
      max-size: ${faramita.file.image.max-size}
  # Github配置
  github:
    branch: main
    name: Nobeta
    email: 377877931@qq.com
    owner: Nobeta-Work
    repo: faramita-bbs-file
    path: img/
    token: ${faramita.github.token}


